name: WLIBC CI/CD

on: [push, pull_request]

jobs:
  msvc-asan:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3
    - name: Install ninja
      shell: cmd
      run: choco install ninja
    - name: Build & Test
      shell: cmd
      run: |
        CALL "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" AMD64
        SET CC=cl
        cmake . -GNinja -DCMAKE_BUILD_TYPE=Debug -DENABLE_ASAN=ON
        ninja
        ctest -VV --repeat until-pass:5
  msvc-release:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3
    - name: Install ninja
      shell: cmd
      run: choco install ninja
    - name: Build & Test
      shell: cmd
      run: |
        CALL "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" AMD64
        SET CC=cl
        cmake . -GNinja -DCMAKE_BUILD_TYPE=Release
        ninja
        ctest -VV --repeat until-pass:5
  clang-release:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3
    - name: Install ninja
      shell: cmd
      run: choco install ninja
    - name: Build & Test
      shell: cmd
      run: |
        SET CC=clang
        cmake . -GNinja -DCMAKE_BUILD_TYPE=Release
        ninja
        ctest -VV --repeat until-pass:5
